### ISSUE TITLE
Create player match list view and player match report view.

### ISSUE THREAD

**Issue by cpascua** [mershon-enterprises/tournament-manager#6]
Build out the player match list view an player match report view.
- [x] player match list view
- [x] player match report view

**Comment by cpascua** [comment]
- [ ] Change the size of the pairing boxes to the size of the red box
  ![resize_pairing_box](https://cloud.githubusercontent.com/assets/2072682/11080794/52ef01c2-87cc-11e5-933a-73180f8aeebf.png)
- [ ] allow ordering by user name or table only
- [ ] allow text to be inputted into the announcement box
- [ ] use an announcement tab that is collapsable at the bottom of the screen, click to expand and collapse
  ![screenshot from 2015-11-10 17 06 15](https://cloud.githubusercontent.com/assets/2072682/11080922/706767ca-87cd-11e5-844e-d8fff4475157.png)

**Comment by krisko6** [comment]
In which box should the user be able to type? The pop-up box, or the announcements box in the center?

**Comment by cpascua** [comment]
@cpauley the announcment pop up box will be replacing the center announcement box, sorry for the confusion.
